name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build 

      - name: Deploy to build branch
        uses: peaceiris/actions-gh-pages@v3.7.0
        with:
          github_token: ${{ secrets.PAT_SECRET }}
          publish_dir: ./dist
          publish_branch: build
          # test
          
      - name: Checkout the build branch
        uses: actions/checkout@v3
        with:
          ref: build  # Replace 'build-branch' with the name of your build branch

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_DROPLET }}

      - name: Copy website build to VPS
        run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete . root@${{ secrets.VPS_IP }}:/var/www/mstfa.co
