name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build 

      - name: Deploy build to build branch
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: build
          folder: dist  # Replace 'dist' with the correct relative path to your build output folder, e.g., 'path/to/dist' ff
          clean: true  # This will remove all files from the build branch that are not part of the new build